repos:
  - repo: https://github.com/myint/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        args: [--in-place, --pre-summary-newline, --close-quotes-on-newline]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.282
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: install
        name: install
        entry: npm --prefix music/frontend install
        files: ".*(vue|ts)"
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: npm --prefix music/frontend run lint
        files: ".*(vue|ts)"
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
