[mypy]
strict = True
disallow_untyped_defs = True
# force argument & return type annotations
disallow_untyped_decorators = True
no_implicit_reexport = False

[mypy-tbhandler.*]
ignore_missing_imports = True
