name: Analyze songs

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  analyze-songs:
    name: Analyze songs
    runs-on: ubuntu-latest
    steps:
      - name: Install package
        uses: quintenroets/actions/setup/environment/@main
        with:
          environment: ci

      - name: Install system dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: ffmpeg

      - name: Run package
        run: spotdl https://open.spotify.com/track/7nc7mlSdWYeFom84zZ8Wr8
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          GENIUS_TOKEN: ${{ secrets.GENIUS_TOKEN }}
          PHONE_CONNECTION: ${{ secrets.PHONE_CONNECTION }}
          RCLONE: ${{ secrets.RCLONE }}
