name: Analyze songs

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  analyze-songs:
    name: Analyze songs
    runs-on: ubuntu-latest
    steps:

      - name: Install package
        uses: quintenroets/actions/setup/environment/@main
        with:
          dependency: git+https://github.com/quintenroets/music.git@run-in-ci

      - name: Install package
        run: pip install git+https://github.com/quintenroets/tbhandler.git@debug

      - name: Install package
        run: install_sitecustomize

      - name: Mount volatile backup drive
        uses: quintenroets/actions/mount-remote/@main
        with:
          remote-name: "backup:home/quinten/Documents/Scripts/assets/music"
          path: "/home/runner/Documents/Scripts/assets/music"
          rclone-secret: ${{ secrets.RCLONE }}

      - name: Mount backup drive
        uses: quintenroets/actions/mount-remote/@main
        with:
          remote-name: "ColumbiaBackup:Music"
          path: "/media/backup/Music"
          rclone-secret: ${{ secrets.RCLONE }}

      - name: Run package
        run: music --no-upload-to-phone
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          GENIUS_TOKEN: ${{ secrets.GENIUS_TOKEN }}
          PHONE_CONNECTION: ${{ secrets.PHONE_CONNECTION }}
