name: Analyze songs

on:
  workflow_dispatch:

jobs:
  analyze-songs:
    name: Analyze songs
    runs-on: ubuntu-latest
    steps:
      - name: Mount volatile backup drive
        uses: quintenroets/actions/mount-remote/@dev
        with:
          remote-name: "backup:home/quinten/Documents/Scripts/assets/music"
          path: "/home/runner/Documents/Scripts/assets/music"
          rclone-secret: ${{ secrets.RCLONE }}

      - name: Mount backup drive
        uses: quintenroets/actions/mount-remote/@dev
        with:
          remote-name: "ColumbiaBackup:Music"
          path: "/media/backup/Music"
          rclone-secret: ${{ secrets.RCLONE }}

      - name: Install package
        uses: quintenroets/actions/setup/environment/@dev
        with:
          dependency: musicmaster

      - name: Run package
        run: music
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          GENIUS_TOKEN: ${{ secrets.GENIUS_TOKEN }}
          PHONE_CONNECTION: ${{ secrets.PHONE_CONNECTION }}
