name: Analyze songs

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  analyze-songs:
    name: Analyze songs
    runs-on: ubuntu-latest
    steps:
      - name: Install package
        uses: quintenroets/actions/setup/environment/@main
        with:
          dependency: git+https://github.com/quintenroets/music.git@change-cache-mode

      - name: Install package
        run: pip install backupmaster

      - name: Install system dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: ffmpeg

      - name: Run package
        run: music
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          GENIUS_TOKEN: ${{ secrets.GENIUS_TOKEN }}
          PHONE_CONNECTION: ${{ secrets.PHONE_CONNECTION }}
