name: Build

env:
  SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
  SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
  GENIUS_TOKEN: ${{ secrets.GENIUS_TOKEN }}
  PHONE_CONNECTION: ${{ secrets.PHONE_CONNECTION }}

on:
  push:

jobs:
  check-pre-commit:
    name: Check pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - name: Check pre-commit hooks
        uses: quintenroets/actions/validate/pre-commit@main

  verify-packaging:
    name: Verify packaging
    runs-on: ubuntu-latest
    steps:
      - name: Verify packaging
        uses: quintenroets/actions/validate/package@main

  extract-python-versions:
    name: Extract Python versions
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.extract-python-versions.outputs.versions }}
    steps:
      - name: Extract Python versions
        id: extract-python-versions
        uses: quintenroets/actions/setup/extract-python-versions@main

  run-tests:
    name: Run tests
    needs: extract-python-versions
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ${{ fromJSON(needs.extract-python-versions.outputs.versions) }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup environment
        id: setup-environment
        uses: quintenroets/actions/setup/environment@main
        with:
          python-version: ${{ inputs.python-version }}
          environment: dev

      - name: Run tests
        shell: bash
        run: |
          export PATH=${{ steps.setup-environment.outputs.environment-path }}:$PATH
          yt-dlp "https://music.youtube.com/watch?v=tJttoZEbvYg"

  publish:
    name: Publish package
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [check-pre-commit, verify-packaging, run-tests]
    environment: release
    permissions:
      id-token: write  # Needed for PyPi publishing
      contents: write  # Needed for GitHub publishing
    steps:
      - name: Publish
        uses: quintenroets/actions/publish@main
