name: Validate

on:
  push:
jobs:
  validate:
    runs-on: ubuntu-latest
    environment: release
    steps:
    - name: Validate
      uses: quintenroets/actions/validate@main
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        GENIUS_TOKEN: ${{ secrets.GENIUS_TOKEN }}
